"""domain/models.py — Entities and Value Objects for Alpha-Signal Extractor.

This defines the core business objects, isolated from frameworks and infrastructure.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class TradeAction(str, Enum):
    """Business rule: Allowed trading actions."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TradingSignal(BaseModel):
    """Value Object representing a trading signal generated by the VLM.
    
    This is what the vision model produces based on chart technicals.
    """
    action: TradeAction = Field(
        description="Trading action: BUY, SELL, or HOLD"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Model confidence score between 0.0 and 1.0"
    )
    entry_price: float = Field(
        gt=0.0,
        description="Suggested entry price for the trade"
    )
    stop_loss: float = Field(
        gt=0.0,
        description="Stop-loss price level for risk management"
    )
    take_profit: float = Field(
        gt=0.0,
        description="Take-profit price target"
    )
    reasoning: str = Field(
        min_length=10,
        description="Brief technical reasoning for the signal"
    )


class SentimentResult(BaseModel):
    """Value Object representing sentiment analysis generated by the text LLM."""
    sentiment: str = Field(
        description="Market sentiment: BULLISH, BEARISH, or NEUTRAL"
    )
    intensity: float = Field(
        ge=0.0, le=1.0,
        description="Sentiment intensity score (0.0 = weak, 1.0 = strong)"
    )
    key_factors: list[str] = Field(
        description="List of key factors driving the sentiment"
    )
    summary: str = Field(
        description="One-sentence summary of the sentiment analysis"
    )


class TradingDecision(BaseModel):
    """Aggregate Root representing the final merged trading decision."""
    vlm_signal: TradingSignal = Field(
        description="Trading signal from the Vision-Language Model"
    )
    sentiment: SentimentResult = Field(
        description="Sentiment analysis from the text LLM"
    )
    final_action: TradeAction = Field(
        description="Final recommended action after merging both signals"
    )
    final_confidence: float = Field(
        ge=0.0, le=1.0,
        description="Merged confidence score"
    )
    meta: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata (timestamps, model versions, etc.)"
    )

    def is_aligned(self) -> bool:
        """Domain logic: checks if VLM signal matches text Sentiment bias."""
        sentiment_direction = {
            "BULLISH": TradeAction.BUY,
            "BEARISH": TradeAction.SELL,
            "NEUTRAL": TradeAction.HOLD,
        }
        sentiment_bias = sentiment_direction.get(self.sentiment.sentiment, TradeAction.HOLD)
        return self.vlm_signal.action == sentiment_bias
